variables:
  - group: credentials

trigger:
  batch: true
  branches:
    include:
      - master
      - features/*
      - fix/*
    exclude:
      - features/experimental/*
  paths:
    exclude:
      - README.md

pr: none

stages:
  - stage: 'Build'
    displayName: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: sbt clean
            displayName: 'Running $ sbt clean'

  - stage: 'Publish'
    displayName: Publish
    #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    condition: succeeded()
    jobs:
      - job: Publish
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            displayName: 'Replacing build number'
            inputs:
              targetType: 'inline'
              script: |
                BRANCH=`echo $(Build.SourceBranch) | rev | cut -d / -f1 | rev`
                BUILD=$(Build.BuildNumber)
                echo ${BRANCH}
                echo ${BUILD}
                sed -i "s/{xxbuildversionxx}/${BRANCH}_${BUILD}/g" build.sbt
                cat build.sbt

          - script: "printf 'realm=https://pkgsprodcus1.pkgs.visualstudio.com/\n host=pkgs.dev.azure.com \n user=dh-platforms-devops \n password=$(maven_password)' > ~/credentials.txt"
            displayName: 'Generate credentials file'
          - script: sbt publish
            displayName: 'Running $ sbt publish'
          - script: "rm ~/credentials.txt"
            displayName: 'Remove credentials file'
