variables:
- group: credentials

trigger:
  batch: true
  branches:
    include:
    - master
    exclude:
    - features/experimental/*
  paths:
    exclude:
    - README.md

pr: none

stages:
- stage: 'Build'
  displayName: Build
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: sbt clean
        displayName: 'Running $ sbt clean'
      - script: sbt update
        displayName: 'Running $ sbt update'
      - script: sbt compile
        displayName: 'Running $ sbt compile'
      - task: DownloadSecureFile@1
        displayName: 'Getting test data'
        inputs:
          secureFile: 'anthillTestData'
      - task: ExtractFiles@1
        displayName: 'Extracting test data'
        inputs:
          archiveFilePatterns: '*.zip'
          destinationFolder: '$(Build.SourcesDirectory)'
          cleanDestinationFolder: false
      - script: sbt test
        displayName: 'Running $ sbt test'

- stage: 'Publish'
  displayName: Publish
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
    - job: Publish
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Bash@3
        displayName: 'Replacing build number'
        inputs:
          targetType: 'inline'
          script: |
            sed -i 's/{xxbuildversionxx}/$(Build.BuildNumber)/g' build.sbt
            cat build.sbt | grep version
      - script: "printf 'realm=https://pkgsprodcus1.pkgs.visualstudio.com/\n host=pkgs.dev.azure.com \n user=dh-platforms-devops \n password=$(maven_password)' > ~/credentials.txt"
        displayName: 'Generate credentials file'
      - script: sbt publish
        displayName: 'Running $ sbt publish'
      - script: "rm ~/credentials.txt"
        displayName: 'Remove credentials file'
